### ISSUE TITLE
Question: are the VLQ methods compatible with the VINT from the EBML spec?

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#6]
Are these compatible?

See this document which describes the VINT:
https://github.com/ietf-wg-cellar/ebml-specification/blob/master/specification.markdown#variable-size-integer

**Comment by StefH** [comment]
I did some testing and it seems these are not compatible.

However when I find the solution, I will post it here.

**Comment by tedd** [comment]
From what I can see they are not.

The VLQ functions use Variable Length Quantity: https://en.wikipedia.org/wiki/Variable-length_quantity 
First bit (signed bit) describes if another octet follows. For signed numbers the second bit of first octet describes negative number.

From what I can see in your link the VINT is implemented similarly, but instead of using first bit of octet it pads 0's before the 1 on first octet.

Something like this (absolutely not tested, just threw together something from what I could see from table under VIND_DATA).

```
public uint VintDecode(Span<byte> b)
{
	var shift = 0;
	uint ret = 0;
	while ((b[0] & (0b1000_0000 >> shift)) != 0)
	{
		if (shift == 0)
			ret = (uint)((uint)b[0] & (uint)0b0111_1111);
		else
			ret = (ret << 8) | b[shift];

		shift++;
	}
	return ret;
}
```

**Comment by tedd** [comment]
Err, I see in next table that the order of bytes have to be reversed for that to work. Weird choices made in the design of that one. :P

**Comment by tedd** [comment]
May be more correct :)

```
void Main()
{
	VintDecode(new byte[] { 0b10000010 }).Dump();
	VintDecode(new byte[] { 0b01000000, 0b00000010 }).Dump();
	VintDecode(new byte[] { 0b00100000, 0b00000000, 0b00000010 }).Dump();
	VintDecode(new byte[] { 0b00010000, 0b00000000, 0b00000000, 0b00000010 }).Dump();
}

public uint VintDecode(Span<byte> b)
{
	uint ret = 0;
	for (var i = 0; i < Math.Min(4,b.Length); i++) {
		ret <<= 8;
		ret |= b[i];
	}
	var lz = ret.LeadingZeroCount(); // "using Tedd;" from Tedd.BitUtils NuGet package
	ret <<= lz + 1;
	ret >>= lz + 1;
	return ret;
}


```

**Comment by StefH** [comment]
@tedd 
I found a solution for VInt by looking at several other source examples like
- https://github.com/OlegZee/NEbml/blob/master/Src/Core/VInt.cs
- https://gitlab.com/nitroxis/matroska


I'll create a PR + add some tests.

**Comment by tedd** [comment]
Thank you. :)
Committed PR and will look into some benchmarking of code when I have more time.
