### ISSUE TITLE
SpanStream : ReadByte returns an int ?

### ISSUE THREAD

**Issue by StefH** [tedd/Tedd.SpanUtils#7]
https://github.com/tedd/Tedd.SpanUtils/blob/a6c71f998be0bace664d6dcc8d255db5ce84622d/src/Tedd.SpanUtils/SpanStream.cs#L394

I think this should be `byte` ?

**Comment by tedd** [comment]
Hi. Thanks for feedback.
This return value is int because of Stream.ReadByte() ([https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readbyte?view=net-5.0](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readbyte?view=net-5.0)) that returns int. MemoryStreamer inherits Stream and therefore is forced to return int (overriding virtual). 

SpanStream mirrors methods in MemoryStreamer, but doesn't inherit from Stream so it could be byte. It should not cause any CPU overhead afaik, but still maybe it should be changed to byte.

**Comment by StefH** [comment]
If you can change it to Byte. That would be nice.

Actually this SpanStream looks a bit like the Sequence reader. https://www.stevejgordon.co.uk/an-introduction-to-sequencereader


---

Other question
Why is the Length property set to 0 initial?

It seems that only MaxLength shows the right value?

**Comment by tedd** [comment]
I've changed ReadByte to byte on SpanReader, but can't do it on MemoryStreamer since it overrides virtual method from Stream. :)
